version: '3'
services:
  react-frontend:
    build:
      context: ./employee_frontend
    ports:
      - "3000:3000"
    networks:
      - ems-network

  ems-backend:
    build:
      context: ./ems-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ems
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - ems-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5
      timeout: 10s
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ems-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5
      timeout: 10s
    restart: always

networks:
  ems-network:
    driver: bridge

volumes:
  postgres-data:
