apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ems-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   
  POSTGRES_DB: ZW1z                  
